# Generated by Django 5.0.3 on 2024-03-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.ManyToManyField(blank=True, max_length=100, related_name='user_addresses', to='management.addres', verbose_name='Dirección'),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company',
        ),
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ManyToManyField(blank=True, max_length=100, related_name='user_companies', to='management.company', verbose_name='Compañia'),
        ),
    ]
