# Generated by Django 5.0.3 on 2024-03-27 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150, verbose_name='Calle')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
                ('country', models.CharField(max_length=60, verbose_name='País')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Nombre de la Compañia')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.addres', verbose_name='Dirección')),
            ],
        ),
    ]
