# Generated by Django 5.0.3 on 2024-03-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_addres_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
